// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0PIHgebnVriCFjlUnAvyys-LkaXcLF8c',
    appId: '1:55770370130:web:b9521193dc027c802d4f8b',
    messagingSenderId: '55770370130',
    projectId: 'proyecto1-31344',
    authDomain: 'proyecto1-31344.firebaseapp.com',
    storageBucket: 'proyecto1-31344.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJTfDfdN9-R9oy6qMC5RT835wsgEzT_X8',
    appId: '1:55770370130:android:773d21b88313e42c2d4f8b',
    messagingSenderId: '55770370130',
    projectId: 'proyecto1-31344',
    storageBucket: 'proyecto1-31344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhVbsVUDrderU5Mc2999iZ6BNd6PtqaXA',
    appId: '1:55770370130:ios:6149096654b54d922d4f8b',
    messagingSenderId: '55770370130',
    projectId: 'proyecto1-31344',
    storageBucket: 'proyecto1-31344.appspot.com',
    iosClientId: '55770370130-p6nrpfa26mht1lrakcp52bsl5knh7pu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto119400618',
  );
}
